services:
  app:
    container_name: wevre-app
    image: wevre
    build:
      dockerfile: Dockerfile
      context: .
      target: test
    command: sh -c '/wait && npm run test:e2e'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - HOST=localhost
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=27017
      - DB_DATABASE=wevre
      # mongo-init.js 파일에서 wevre 데이터베이스에 해당하는 사용자와 비밀번호를 생성한다.
      - DB_USERNAME=csup
      - DB_PASSWORD=csup
      - DB_LOGGING=true
      - JWT_ACCESS_TOKEN_SECRET=wevre-jwt-access-token
      - JWT_ACCESS_TOKEN_EXPIRATION=1800000
      - JWT_REFRESH_TOKEN_SECRET=wevre-jwt-refresh-token
      - JWT_REFRESH_TOKEN_EXPIRATION=86400000
      - CACHE_TTL=180
      - CACHE_MAX=1000
      - SOCKET_SESSION_EXPIRATION=86400000
      - SOCKET_SESSION_TTL=86400
      - REDIS_HOST=cache
      - REDIS_PORT=6379
      - NAVER_CLIENT_ID=naver-client-id
      - NAVER_CLIENT_SECRET=naver-client-secret
      - NAVER_CALLBACK_URI=naver-callback-uri
      - GOOGLE_CLIENT_ID=google-client-id
      - GOOGLE_CLIENT_SECRET=google-client-secret
      - GOOGLE_CALLBACK_URI=google-callback-uri
      - WAIT_HOSTS=db:27017
      - WAIT_TIMEOUT=600
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=10
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      disable: true

  db:
    container_name: wevre-db
    image: mongo:6.0.7
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=wevre
    volumes:
      - ./seed/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - db:/data/db
    healthcheck:
      test: '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/wevre --quiet` ] && echo 0 || echo 1'
      interval: 5s
      timeout: 4s
      retries: 5
      start_period: 5m

  seed:
    container_name: wevre-seed
    image: seed
    build:
      dockerfile: Dockerfile
      context: ./seed

  cache:
    container_name: wevre-cache
    image: redis:7.2.4-alpine
    ports:
      - '6379:6379'

volumes:
  db:
