name: Test the application
on: push

env:
  DOCKER_IMAGE_TEST: csup96/wevre-test:latest

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build a Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          target: test
          tags: ${{ env.DOCKER_IMAGE_TEST }}

      - name: Run unit tests with a Docker container
        run: docker container run --rm ${{ env.DOCKER_IMAGE_TEST }}
